// questions.js
const QUESTIONS = [
  { q: "What's my favorite color?", options: ["Red", "Blue", "Green", "Yellow"] },
  { q: "What's my favorite food?", options: ["Pizza", "Rice", "Burgers", "Pasta"] },
  { q: "Where would I love to travel?", options: ["Paris", "New York", "Tokyo", "Dubai"] },
  { q: "What's my dream job?", options: ["Doctor", "Engineer", "Actor", "Artist"] },
  { q: "Am I more introvert or extrovert?", options: ["Introvert", "Extrovert"] },
  { q: "What's my favorite sport?", options: ["Football", "Basketball", "Tennis", "Swimming"] },
  { q: "Which pet do I like most?", options: ["Dog", "Cat", "Parrot", "Fish"] },
  { q: "Do I like tea or coffee?", options: ["Tea", "Coffee"] },
  { q: "Am I a morning or night person?", options: ["Morning", "Night"] },
  { q: "My favorite subject in school?", options: ["Math", "English", "Science", "Art"] },
  { q: "What’s my favorite drink?", options: ["Coke", "Pepsi", "Juice", "Water"] },
  { q: "Do I prefer summer or winter?", options: ["Summer", "Winter"] },
  { q: "My favorite ice cream flavor?", options: ["Vanilla", "Chocolate", "Strawberry", "Mint"] },
  { q: "Do I like movies or series more?", options: ["Movies", "Series"] },
  { q: "What’s my dream car?", options: ["Tesla", "BMW", "Mercedes", "Toyota"] },
  { q: "Do I like spicy food?", options: ["Yes", "No"] },
  { q: "What's my favorite holiday?", options: ["Christmas", "New Year", "Eid", "Halloween"] },
  { q: "Do I prefer books or games?", options: ["Books", "Games"] },
  { q: "What's my favorite music genre?", options: ["Pop", "Hip-Hop", "Rock", "Classical"] },
  { q: "Do I like beaches or mountains?", options: ["Beaches", "Mountains"] },
  { q: "Do I prefer Android or iOS?", options: ["Android", "iOS"] },
  { q: "Am I good at cooking?", options: ["Yes", "No"] },
  { q: "Do I like sweet or salty snacks?", options: ["Sweet", "Salty"] },
  { q: "Do I like online shopping?", options: ["Yes", "No"] },
  { q: "Do I prefer staying in or going out?", options: ["Staying in", "Going out"] },
  { q: "What's my lucky number?", options: ["1", "3", "7", "9"] },
  { q: "What kind of movies do I like?", options: ["Action", "Comedy", "Romance", "Horror"] },
  { q: "Do I like rain?", options: ["Yes", "No"] },
  { q: "My favorite fruit?", options: ["Apple", "Banana", "Mango", "Orange"] },
  { q: "Do I like shopping alone or with friends?", options: ["Alone", "With friends"] },
  { q: "Am I more of a leader or follower?", options: ["Leader", "Follower"] },
  { q: "Do I like big cities or small towns?", options: ["Big cities", "Small towns"] },
  { q: "Do I like swimming?", options: ["Yes", "No"] },
  { q: "Do I like cooking or eating more?", options: ["Cooking", "Eating"] },
  { q: "Do I prefer text or calls?", options: ["Text", "Calls"] },
  { q: "Do I like music loud or soft?", options: ["Loud", "Soft"] },
  { q: "Do I like sunrise or sunset?", options: ["Sunrise", "Sunset"] },
  { q: "Do I prefer hot or cold weather?", options: ["Hot", "Cold"] },
  { q: "Am I good at keeping secrets?", options: ["Yes", "No"] },
  { q: "Do I like travelling by car or plane?", options: ["Car", "Plane"] },
  { q: "Do I like fast food?", options: ["Yes", "No"] },
  { q: "Do I like dancing?", options: ["Yes", "No"] },
  { q: "Do I prefer short hair or long hair?", options: ["Short", "Long"] },
  { q: "Do I like mornings or evenings?", options: ["Mornings", "Evenings"] },
  { q: "Do I like sweet drinks or water?", options: ["Sweet drinks", "Water"] },
  { q: "Do I like chocolate?", options: ["Yes", "No"] },
  { q: "Do I like camping?", options: ["Yes", "No"] },
  { q: "Do I like ice cream?", options: ["Yes", "No"] },
];