// questions.js

const allQuestions = [
    { question: "What is my favorite color?", options: ["Red", "Blue", "Green", "Yellow"] },
    { question: "Which season do I like the most?", options: ["Summer", "Winter", "Spring", "Autumn"] },
    { question: "What is my favorite food?", options: ["Pizza", "Burger", "Rice", "Pasta"] },
    { question: "Which pet would I prefer?", options: ["Dog", "Cat", "Bird", "None"] },
    { question: "Am I more of a morning person or night owl?", options: ["Morning", "Night"] },
    { question: "What is my favorite drink?", options: ["Coffee", "Tea", "Juice", "Water"] },
    { question: "Which sport do I enjoy watching most?", options: ["Football", "Basketball", "Tennis", "None"] },
    { question: "If I could travel anywhere, where would I go?", options: ["Paris", "New York", "Tokyo", "Dubai"] },
    { question: "What’s my dream job?", options: ["Doctor", "Engineer", "Artist", "Entrepreneur"] },
    { question: "Do I like sweet or savory snacks?", options: ["Sweet", "Savory"] },
    { question: "Which genre of music do I love most?", options: ["Pop", "Hip-Hop", "Rock", "Classical"] },
    { question: "What’s my favorite ice cream flavor?", options: ["Vanilla", "Chocolate", "Strawberry", "Mint"] },
    { question: "Which movie genre do I enjoy most?", options: ["Action", "Comedy", "Romance", "Horror"] },
    { question: "What’s my favorite fruit?", options: ["Mango", "Apple", "Banana", "Orange"] },
    { question: "Which game do I prefer?", options: ["Football", "Basketball", "Volleyball", "Tennis"] },
    { question: "What type of movies do I dislike?", options: ["Horror", "Romance", "Comedy", "Action"] },
    { question: "Which subject was my favorite in school?", options: ["Math", "English", "Science", "History"] },
    { question: "Do I prefer the beach or mountains?", options: ["Beach", "Mountains"] },
    { question: "What’s my favorite cake flavor?", options: ["Chocolate", "Vanilla", "Red Velvet", "Cheesecake"] },
    { question: "Which superhero do I like most?", options: ["Spider-Man", "Batman", "Iron Man", "Superman"] },
    { question: "Am I more into books or movies?", options: ["Books", "Movies"] },
    { question: "Do I enjoy dancing?", options: ["Yes", "No"] },
    { question: "Which fast food restaurant do I like best?", options: ["McDonald's", "KFC", "Burger King", "Subway"] },
    { question: "Do I like rainy days?", options: ["Yes", "No"] },
    { question: "Which drink do I dislike?", options: ["Coffee", "Tea", "Soda", "Milk"] },
    { question: "What’s my favorite holiday?", options: ["Christmas", "New Year", "Eid", "Valentine’s Day"] },
    { question: "Do I like spicy food?", options: ["Yes", "No"] },
    { question: "Which language would I like to learn?", options: ["Spanish", "French", "Japanese", "German"] },
    { question: "What’s my favorite board game?", options: ["Chess", "Monopoly", "Scrabble", "Ludo"] },
    { question: "Which flower do I like best?", options: ["Rose", "Tulip", "Sunflower", "Lily"] },
    { question: "Do I prefer texting or calling?", options: ["Texting", "Calling"] },
    { question: "What’s my favorite dessert?", options: ["Cake", "Ice Cream", "Pudding", "Cookies"] },
    { question: "Do I enjoy camping?", options: ["Yes", "No"] },
    { question: "What’s my favorite hobby?", options: ["Reading", "Gaming", "Cooking", "Drawing"] },
    { question: "Am I an introvert or extrovert?", options: ["Introvert", "Extrovert"] },
    { question: "What’s my favorite drink brand?", options: ["Coca-Cola", "Pepsi", "Fanta", "Sprite"] },
    { question: "Which app do I use most?", options: ["Instagram", "WhatsApp", "TikTok", "YouTube"] },
    { question: "Do I like shopping?", options: ["Yes", "No"] },
    { question: "Which ice cream topping do I like?", options: ["Sprinkles", "Chocolate Syrup", "Nuts", "Whipped Cream"] },
    { question: "Do I like traveling?", options: ["Yes", "No"] },
    { question: "Which ride do I enjoy at amusement parks?", options: ["Roller Coaster", "Ferris Wheel", "Bumper Cars", "Haunted House"] },
    { question: "What’s my dream car?", options: ["Tesla", "Ferrari", "Lamborghini", "BMW"] },
    { question: "Do I prefer hot or cold weather?", options: ["Hot", "Cold"] },
    { question: "What’s my favorite TV show genre?", options: ["Drama", "Comedy", "Reality", "Documentary"] },
    { question: "Do I like wearing sneakers or sandals?", options: ["Sneakers", "Sandals"] },
    { question: "What’s my favorite chocolate?", options: ["KitKat", "Snickers", "Mars", "Twix"] },
    { question: "Do I prefer Netflix or YouTube?", options: ["Netflix", "YouTube"] },
    { question: "Which meal do I like most?", options: ["Breakfast", "Lunch", "Dinner"] },
    { question: "Do I like trying new foods?", options: ["Yes", "No"] }
];